name: Python Test and Code Coverage

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pylint
          pip install -U Flask
          pip install -U flask-cors
          pip install pytest pytest-cov codecov

      - name: Run tests and generate coverage report
        id: pyTest
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term
        continue-on-error: true  # Continue to the next step even if the test one fails

      - name: Upload coverage to Codecov
        if: always()  # Ensure this step runs regardless of test results
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml  # Path to the coverage report generated by pytest-cov

      - name: Fail the job when tests fail
        if: ${{ steps.pyTest.outcome == 'failure' }}
        run: exit 1
