name: Update Commit Count Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:       # Allows manual triggering of workflow

jobs:
  update-commit-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get total commit count
        id: commit_count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_ENV

      - name: Update README with commit count
        run: |
          sed -i "s/COMMITS_COUNT/${{ env.commit_count }}/g" README.md

      - name: Verify README content
        run: cat README.md  # Shows README content for debugging

      - name: Commit changes if there are any
        run: |
          git config --local user.email "sathwik.palakurty@gmail.com"
          git config --local user.name "github-actions"
          git add README.md
          git diff --cached  # Check if there are changes
          git commit -m "Update commit count badge in README" || echo "No changes to commit"
          git push || echo "Nothing to push"
