name: Update Commit Count Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:       # Allows manual triggering of workflow

jobs:
  update-commit-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get total commit count
        id: commit_count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Total commits: $COMMIT_COUNT"

      - name: Update README with commit count badge
        run: |
          # Replace placeholder with actual commit count badge link
          echo "Updating README.md with the new commit count"
          COMMIT_BADGE="![Total commits](https://img.shields.io/badge/Commits-${{ env.commit_count }}-blue)"
          # Use echo to write directly, replacing entire line for reliability
          sed -i "s|![Total commits](.*)|$COMMIT_BADGE|" README.md
          cat README.md  # Check README content

      - name: Commit changes if there are any
        run: |
          git config --local user.email "sathwik.palakurty@gmail.com"
          git config --local user.name "github-actions1"
          git add README.md
          git diff --cached  # Show staged changes
          git commit -m "Update commit count badge in README" || echo "No changes to commit"
          git push || echo "Nothing to push"
