name: Update Commit Count Badge

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  update-commit-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get total commit count
        id: commit_count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV  # Use the new method to set environment variables

      - name: Generate commit count badge
        uses: emibcn/badge-action@v1
        with:
          label: "Commits"
          status: "${{ env.COMMIT_COUNT }}"  # Use 'status' instead of 'message'
          color: "blue"
          path: "badges/commits-badge.svg"  # Saves badge to badges folder

      - name: Commit changes if there are any
        run: |
          git config --local user.email "sathwik.palakurty@gmail.com"
          git config --local user.name "github-actions"
          git add badges/commits-badge.svg
          git commit -m "Update commit count badge" || echo "No changes to commit"
          git push || echo "Nothing to push"

