name: Update Issue Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:    # Allows manual triggering of workflow

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch issue counts
        id: issue_counts
        run: |
          OPEN_ISSUES=$(curl -s https://api.github.com/repos/SE-Fall2024/MovieRecommender | jq '.open_issues_count')
          CLOSED_ISSUES=$(curl -s https://api.github.com/repos/SE_Fall2024/MovieRecommender/issues?state=closed | jq 'length')
          echo "open_issues=$OPEN_ISSUES" >> $GITHUB_ENV
          echo "closed_issues=$CLOSED_ISSUES" >> $GITHUB_ENV

      - name: Update README with badge
        run: |
          sed -i "s/OPEN_ISSUES/${{ env.open_issues }}/g" README.md
          sed -i "s/CLOSED_ISSUES/${{ env.closed_issues }}/g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "sathwik.palakurty@gmail.com"
          git config --local user.name "github-actions"
          git add README.md
          git commit -m "Update issue badges in README"
          git push
