name: Run Tests

on: 
  push:
    branches: ["main"]  # Triggers on commits to the main branch
  pull_request:
    branches: ["main"]  # Triggers on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pylint
          pip install -U Flask
          pip install -U flask-cors
          pip install pytest

      - name: Running test cases for searching
        run: python test/test_search_functionality.py
        continue-on-error: true  

      - name: Running test cases for util
        run: python test/tests.py
        continue-on-error: true  
